DROP DATABASE IF EXISTS RequestEnvelop;
CREATE DATABASE RequestEnvelop;
USE RequestEnvelop;

CREATE TABLE User(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  password VARCHAR(255),
  money BIGINT NOT NULL,
  remainTimes INT(10) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE Envelop(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  price BIGINT(60) NOT NULL ,
  isUsed BOOLEAN NOT NULL
) ENGINE = InnoDB;